### ISSUE TITLE
Uchar and Achar Implementation

### ISSUE THREAD

**Issue by Druidpeter** [nicrohobak/AnsiGL#3]
Hey, Nicrohobak,

I'm looking at the code you wrote, and I see that achar and uchar classes don't have any member variables. Since the documentation states that uchars and achars are essentially character glyphs and character glyphs paired with ansi codes, I'm wondering how you are actually storing characters inside uchars and achars?

Also, do you have any reliable contact information? I'm operating in good faith on the assumption that this repository isn't dead, though it does appear the last commit was about 2 years ago. I hope to hear from you.

Druidpeter.

**Comment by nicrohobak** [comment]
Hi Druidpeter,

The AnsiGL::uchar class actually has one member (defined near the
bottom, since it's 'protected' and not 'public'): std::string _UTF8;

That std::string should only contain the equivalent of "one glyph" at
any given point, but since a UTF-8 string can be more than a single
'char', it's just defined this way instead.

The AnsiGL::achar class basically just expands upon AnsiGL::uchar with
the addition of the AnsiGL::ANSICodeList, which ultimately just gets
rendered out properly during rendering, but just isn't directly
embedded into the glyph (IIRC, for better compatibility when one opts
to turn ANSI color off, etc.).

This contact info here is still pretty reliable, and while I haven't
actively worked on this in a while (and I honestly feel like it could
use a bit of modernization at this point too), feel free to get in
touch at any time for any questions you may have.  I have absolutely no
problem at all continuing to provide support if I can.  Just let me
know if there's anything else I can help with!

**Comment by Druidpeter** [comment]
Ah! All right. Cool. That clears things up well. So, I've forked your repository, and am in the process of setting up automated Doxygen markup documentation within the source code so that documentation can be generated automatically. I'm also using this as an exercise to really understand your code as best I can, so I'll be pestering you for clarifications like I did just now every now and then, lol.

When I'm done, I'll send you a pull request so you can review.

**Comment by nicrohobak** [comment]
A follow-up thought that may help in reading the code too..

When defining classes, I try to make them as "self-documenting" as
possible, but the general philosophy is something like...the closer to
the top something is defined, the more likely it will be for you to be
interested in it in general use.

So, the definition tends to be something like:

class
  - public members
  - public functions
  - constructors/operators
  - protected members
  - protected functions
  - private members
  - private functions

Protected and private members often get an underscore as a
prefix...capitalization is also a factor...  I don't remember all of
the philosophy I was running with at the time, but there was indeed a
method to the madness.  Hope this helps too.

**Comment by nicrohobak** [comment]
Awesome, sounds great!

**Comment by Druidpeter** [comment]
Ah! All right. Cool. That clears things up well. So, I've forked your repository, and am in the process of setting up automated Doxygen markup documentation within the source code so that documentation can be generated automatically. I'm also using this as an exercise to really understand your code as best I can, so I'll be pestering you for clarifications like I did just now every now and then, lol.

When I'm done, I'll send you a pull request so you can review.
